env: "dev"

http_server:
  host: "localhost"
  port: "8000"
  read_timeout: "15s"
  write_timeout: "15s"

postgres:
  host: ""
  port: ""
  user: ""
  passwd: ""
  db_name: ""
  ssl_mode: ""

token:
  maxage: 
  expired_in: ""
  jwt_token_secret: ""